# This Pipeline is created to test the connections to the ORG
# V 1.0
# Author : Shailendra V

trigger: none

parameters:
- name: Environment
  type: string
  default: 'Dev'
  values:
   - Dev
   - Test
   - QA
   - UAT
   - PROD

variables:
- name: ConnectionStringDEV
  value: 'AuthType=ClientSecret;ClientId=$(cds_appid);ClientSecret=$(cds_secret);Url=https://nwenteractdev.$(cds_region).dynamics.com'
- name: ConnectionStringUAT
  value: 'AuthType=ClientSecret;ClientId=$(UATcds_appid);ClientSecret=$(UATcds_secret);Url=https://nwenteractuat.$(cds_region).dynamics.com'
- name: ConnectionStringQA
  value: 'AuthType=ClientSecret;ClientId=$(UATcds_appid);ClientSecret=$(UATcds_secret);Url=https://nwenteractqa.$(cds_region).dynamics.com'
- name: ConnectionStringTest
  value: 'AuthType=ClientSecret;ClientId=$(cds_appid);ClientSecret=$(cds_secret);Url=https://nwenteracttest.$(cds_region).dynamics.com'
- name: ConnectionString
  value: '$(ConnectionString${{parameters.Environment}}')


jobs:
- job: PROD
  steps:
  - script:
    echo $(ConnectionString)