parameters:
- name: Environment
  type: string
  default: 'Dev'
  values:
   - Dev
   - Test
   - QA
   - UAT
   - PROD


trigger: none

jobs:

- ${{ if contains(parameters.Environment, 'Dev') }}:
  - job: Dev
    steps:
    - script: echo Dev
    - task: CmdLine@2
      inputs:
        script: |
            echo "HI"

- ${{ if contains(parameters.Environment, 'Test') }}:
  - job: Test
    steps:
    - script: echo Test

- ${{ if contains(parameters.Environment, 'QA') }}:
  - job: QA
    steps:
    - script: echo QA

- ${{ if contains(parameters.Environment, 'UAT') }}:
  - job: UAT
    steps:
    - script: echo UAT

- ${{ if contains(parameters.Environment, 'PROD') }}:
  - job: PROD
    steps:
    - script: echo PROD
